CREATE TABLE endereco (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	cep varchar,
	logradouro text NULL,
	bairro text NULL,
	cidade text NULL,
	estado text NULL,
	created_at timestamptz DEFAULT now(),
	updated_at timestamptz DEFAULT now(),
	deleted_at timestamptz DEFAULT NULL
);

CREATE INDEX busca_cep_endereco ON public.endereco(cep) INCLUDE (cidade) WHERE deleted_at IS NULL;

CREATE TABLE usuario (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome text NOT NULL,
	sobrenome text NOT NULL,
	nome_usuario varchar(35) UNIQUE NOT NULL,
	email text UNIQUE NOT NULL,
	senha_hash text NOT NULL,
	cpf varchar(14) UNIQUE NOT NULL,
	data_nascimento date NOT NULL,
	bio jsonb,
	imagem_perfil_url text,
	status text,
	endereco_id bigint REFERENCES public.endereco(id),
	created_at timestamptz DEFAULT now(),
	updated_at timestamptz DEFAULT now(),
	deleted_at timestamptz DEFAULT NULL
);

CREATE INDEX busca_usuario_endereco ON
public.usuario (nome_usuario) INCLUDE (endereco_id)
WHERE
deleted_at IS NULL;

CREATE TABLE usuario_amizade (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	usuario_origem_id bigint REFERENCES public.usuario(id),
	usuario_destino_id bigint REFERENCES public.usuario(id),
	status text,
	created_at timestamptz DEFAULT now(),
	updated_at timestamptz DEFAULT now(),
	deleted_at timestamptz DEFAULT NULL
);

CREATE UNIQUE INDEX usuario_amizade_solicitacao ON
public.usuario_amizade(
	usuario_origem_id,
	usuario_destino_id
)
WHERE
deleted_at IS NULL;

CREATE TABLE publicacao (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	usuario_id bigint REFERENCES public.usuario(id),
	conteudo text,
	imagem_url text NULL,
	status text,
	created_at timestamptz DEFAULT now(),
	updated_at timestamptz DEFAULT now(),
	deleted_at timestamptz DEFAULT NULL
);

CREATE INDEX usuario_publicacao ON
public.publicacao (
	usuario_id
) INCLUDE (conteudo, imagem_url)
WHERE
deleted_at IS NULL;

CREATE TABLE comentario (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	publicacao_id bigint REFERENCES public.publicacao(id),
	usuario_id bigint REFERENCES public.usuario(id),
	conteudo text,
	created_at timestamptz DEFAULT now(),
	updated_at timestamptz DEFAULT now(),
	deleted_at timestamptz DEFAULT NULL
);

CREATE INDEX usuario_comentario_em_publicacao ON
public.comentario (
	usuario_id,
	publicacao_id
) INCLUDE (conteudo)
WHERE
deleted_at IS NULL;

CREATE TABLE conversa (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uuid text,
	created_at timestamptz DEFAULT now(),
	updated_at timestamptz DEFAULT now(),
	deleted_at timestamptz DEFAULT NULL
);

CREATE TABLE conversa_mensagem (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uuid text,
	conversa_id bigint REFERENCES public.conversa(id),
	usuario_id bigint REFERENCES public.usuario(id),
	mensagem jsonb,
	status text,
	created_at timestamptz DEFAULT now(),
	updated_at timestamptz DEFAULT now(),
	deleted_at timestamptz DEFAULT NULL
);

CREATE TABLE conversa_participante (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uuid text,
	conversa_id bigint REFERENCES public.conversa(id),
	usuario_id bigint REFERENCES public.usuario(id),
	created_at timestamptz DEFAULT now(),
	updated_at timestamptz DEFAULT now(),
	deleted_at timestamptz DEFAULT NULL
);
